// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd4jpPYamjet6KeYjL0wvNtfVYO6DEYOA',
    appId: '1:1068045310611:android:4ad2a8c868cf946f420b66',
    messagingSenderId: '1068045310611',
    projectId: 'sushibar-949c3',
    storageBucket: 'sushibar-949c3.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQ6r64l69LgWlANoJyt3RNcpBeq2hvL8',
    appId: '1:1068045310611:web:4193768a140ca4f6420b66',
    messagingSenderId: '1068045310611',
    projectId: 'sushibar-949c3',
    authDomain: 'sushibar-949c3.firebaseapp.com',
    storageBucket: 'sushibar-949c3.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDo32aDVvsTnkBxT1CSA8bbe97w5RhDEY',
    appId: '1:1068045310611:ios:479e58678d055bb7420b66',
    messagingSenderId: '1068045310611',
    projectId: 'sushibar-949c3',
    storageBucket: 'sushibar-949c3.appspot.com',
    iosBundleId: 'com.example.sushiShop',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDo32aDVvsTnkBxT1CSA8bbe97w5RhDEY',
    appId: '1:1068045310611:ios:479e58678d055bb7420b66',
    messagingSenderId: '1068045310611',
    projectId: 'sushibar-949c3',
    storageBucket: 'sushibar-949c3.appspot.com',
    iosBundleId: 'com.example.sushiShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYQ6r64l69LgWlANoJyt3RNcpBeq2hvL8',
    appId: '1:1068045310611:web:955cbf3dc447b470420b66',
    messagingSenderId: '1068045310611',
    projectId: 'sushibar-949c3',
    authDomain: 'sushibar-949c3.firebaseapp.com',
    storageBucket: 'sushibar-949c3.appspot.com',
  );

}